// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalCloseController from "./modal_close_controller"
application.register("modal-close", ModalCloseController)

import CurrencyController from "./currency_controller"
application.register("currency", CurrencyController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import SnackbarController from "./snackbar_controller"
application.register("snackbar", SnackbarController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import PreservePositionController from "./preserve_position_controller"
application.register("preserve-position", PreservePositionController)

import ReorderModeController from "./reorder_mode_controller"
application.register("reorder-mode", ReorderModeController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import PickerController from "./picker_controller"
application.register("picker", PickerController)
